Add README
shellixyz/fc_calibration_tool pull request #1
Opened 2021-09-11 17:53 UTC by skorokithakis

2021-09-11 19:14 UTC, shellixyz requested changes
Good start

2021-09-11 19:14 UTC, shellixyz commented on README.md
> +This is a tool that helps calibrate INAV FCs.
It can also calibrate FCs with Ardupilot installed

2021-09-11 19:14 UTC, shellixyz commented on README.md
> +$ sudo gem install serialport crc
Now that I added a Gemfile you can simply do `bundle install` to install all the dependencies. It also depends on nokogiri for parsing Mavlink messages definitions stored in XML files

2021-09-11 19:14 UTC, shellixyz commented on README.md
> +Keep in mind that you need to connect to the FC **without connecting power**. You can
Would be nice to specify power through USB and why it is not wise to do it: it will influence the readinds of the current sensor

2021-09-11 20:39 UTC, skorokithakis commented
I've addressed the feedback, thanks!

2021-09-14 17:04 UTC, shellixyz approved these changes

2021-09-14 17:05 UTC, merged